### ISSUE TITLE
Bug? Bestand niet vervangen bij change

### ISSUE THREAD

**Issue by rmens** [rmens/regio#6]
Een gebruiker zegt:

> Maar ik upload net een nieuwe file in een bericht
> En dat veranderd hij niet
> Blijft dezelfde file
> In de database dus

Even testen

**Comment by marijnvdwerf** [comment]
Zou er aan kunnen liggen dat `edit.ctp` geen `, ['type' => 'file']` meegeeft

```
    <?= $this->Form->create($message) ?>
    <?= $this->Form->create($message, ['type' => 'file']) ?>
```
